modsed: use follow-symlinks for sed

diff --git a/tools/freetz_functions b/tools/freetz_functions
--- a/tools/freetz_functions
+++ b/tools/freetz_functions
@@ -205,7 +205,7 @@ modsed() {
 	for f in $2; do
 		echo2 "patching $f"
 		[ ! -f "$f" ] && continue || let c++
-		sed -i $extended_regexp -e "$1" "$f" || error 1 "modsed failed editing $f (bad sed syntax?)"
+		sed --follow-symlinks -i $extended_regexp -e "$1" "$f" || error 1 "modsed failed editing $f (bad sed syntax?)"
 		if [ $# -ge 3 ]; then
 			grep -q "$3" "$f" || error 1 "modsed failed editing $f"
 		fi
